### ISSUE TITLE
haptic moto v0.9

### ISSUE THREAD

**Issue by michaelSwiss** [Seeed-Studio/Grove_Haptic_Motor#2]
hello,

Many thx for sharing this code.
I tried on a Arduino with an Haptic Motor v0.9 (written on the back of the module) and the code did not work.
I get following error (printed on the serial screen)
initinit failed!
auto calibration failed!
Effect No: 1
Effect No: 2
Effect No: 3

In case you know what the issue could be - many thx,
PLease note that I am a very basic user but managed to bring most components I have to live :-)
regards,
Michael

**Comment by Regelink** [comment]
Sorry Michael, I forgot to revert the example to use the Wire I2C by default. In the example make a call to haptic.init(**false**, true) instead of haptic.init(**true**, true) in order to used the original Arduino I2C interface pins.

**Comment by michaelSwiss** [comment]
Hello, thx for taking the time…. given I am a very new & basic user I have not fully understood the above. I copied the example code proposed but the  only line I see with what you mentionned is this one:
    if (haptic.init(false, true) != 0) Serial.println("init failed!");
But it is already "false".
I suspect I miss understood you….
Thx,
regards,
Michael

**Comment by Regelink** [comment]
Right before posting my previous comment I filed a pull request to change the code on GitHub, so if you looked at the GitHub code after [that change](https://github.com/Seeed-Studio/Grove_Haptic_Motor/commit/8548b5b8e7164a4d33109ab3acdf5149bbd21102) was accepted (yesterday) then you'll notice that the line already is _if (haptic.init(false, true) != 0) Serial.println("init failed!");_.

Now the question is, did you check the code on your local computer? And did you actually try it with the first argument set to false? Unfortunately I cannot test it anymore right now (I have tested it though) since I did this implementation for someone else. I haven't got the hardware myself.

**Comment by michaelSwiss** [comment]
great it works I just tested it adding the line you did. Many thx !

**Comment by michaelSwiss** [comment]
Now that it works (thanks again), I in fact have one more question, do you know how I can make it vibrate for some time then turn off for some time? With another motor type I used the below code and I would like to repeat a similar pattern with the haptic motor but do not manage to to it. 
    digitalWrite(MoPinLeft, HIGH);  
    delay(50);  
    digitalWrite(MoPinLeft, LOW);  
    delay(2000)

**Comment by Regelink** [comment]
Michael,

For my application playing specific waveforms from the built-in sequencer (like in the example) was sufficient, so I did not dig into that any further. Looking in the [datasheet of the DRV2605L](http://www.ti.com/product/DRV2605L), my first guess is that you'll need to use the **RTP** mode. I think the only hardware connections between the DRV2605L and your Arduino is the I2C bus and power supply (so I'm afraid no other hardware pins like assumed in your code snippet are available for controlling the device).

I wish you good luck and hope you can figure it out, and when you do, maybe you can implement that functionality into this driver and share it on GitHub!

Best regards,
Bert
